### ISSUE TITLE
Missing info when currentAd page is refreshed

### ISSUE THREAD

**Issue by BrunoHautenfaust** [TeamFeijoa-JsApps/FeijoaCars#13]
When the user is on the currentAd page (ex. myAds/590794e8461a4f3563a07c02) and refreshes the page, no data shows up. The GET request has lost the "Id" parameter. I tried adding localStorage but for some reason it doesn't work. I have doubts that the value is even stored successfully in the localStorage. Methods are correct:
localStorage.setItem('key', value);
localStorage.getItem('key');

**Comment by cmdkick** [comment]
The same happens when you refresh the MyProfile page #/profile/59052d524874ceee2b22fe48.
